### ISSUE TITLE
Unable to import styes on OSX

### ISSUE THREAD

**Issue by tuvokki** [elgervb/skeletonSPA#38]
OSX is somewhat more picky about slashes when it comes to filenames. The import of the skeleton styles is wrong:

    @import 'modules\skeleton';

Fix it by changing the backslash to a forward one (like the partials imports already do):

    @import 'modules/skeleton';

**Comment by elgervb** [comment]
@tuvokki Please review this commit, so I can merge with Master

**Comment by tuvokki** [comment]
This will work
